### ISSUE TITLE
Roadmap-ish

### ISSUE THREAD

**Issue by fstephany** [packler-rs/packler#1]
## 0.2.0

0.2 still focuses on assets (CSS/images). 

- [ ] Configurable assets deploy (hardcoded right now)
- [ ] Expose a non async API. The user shouldn't need to add tokio as a dep to their xtask

## 0.3.0

- [ ] Logging system (how to separate different processes)
- [ ] Remove async where it's not absolutely necessary
- [ ] Feature gating (e.g., assets deploy should be a feature) 

## 0.4.0

- [ ] Hook system to customize data before/after each step.
- [ ] Documentation

## 0.5.0

Focus on building other parts (server, wasm frontend, lambdas)
